name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Server

    steps:
      - uses: actions/checkout@v3
      - name: "Create env file"
        run: echo "${{ secrets.TOEICTESTING247_ENV_PRODUCTION }}" > .env.production
      - name: Build the Docker image
        run: docker build --progress=plain -t nguyenminhquang01/toeictesting247:v1 .
